'**內容控制項(Content Control)儲存成.docx，會有問題

'    late binding
    Dim objword As Object
    Set objword = CreateObject("Word.Application")

    Dim objdoc As Object
 
'打開已存在的word，並指定給物件
    Set objdoc = objword.documents.Open("D:\Karen\成長冊_特助\三階生活花絮3月體能OK.docm")
    
'在書籤標示位置插入excel儲存格資料
    objdoc.bookmarks("班級").Range.Text = student.Cells(2, 1).Value
    objdoc.bookmarks("姓名").Range.Text = student.Cells(2, 2).Value
    objdoc.bookmarks("日期").Range.Text = student.Cells(2, 3).Value
    
'釋放物件
    Set objword = Nothing
    Set objdoc = Nothing
    
    Dim fileexist As String
    
'word會顯現，新增一個word2檔
    objword.Visible = True 
    Set objdoc = objword.documents.Add()
    
'另存新檔
    objword.activedocument.SaveAs Filename:="path"
    
'關閉word檔(在excel怪怪的，word沒試過)
    objword.objdoc.Close()
    objword.quit()
    
'在word插入文字及段落
    objword.Content.InsertAfter "Text"
    objword.Content.InsertParagraphAfter
    
'確認書籤存在
    If objword.bookmarks.exists("bookmarkname") = True Then
    End If

'在選定位置新控制項
    Selection.Range.ContentControls.Add (wdContentControlPicture)

'設定圖片格式
Sub adjustPictSize()
    Dim picWidth As Integer
    Dim picHeight As Integer
    Dim oIshp As InlineShape

    picHeight = 3.42 * 28.32
    picWidth = 6.1 * 28.32

    For Each oIshp In ActiveDocument.InlineShapes
        With oIshp
            .LockAspectRatio = msoFalse
            .Height = picHeight
            .Width = picWidth
        End With
    Next oIshp
End Sub

'讀取控制項的內容
    Dim DocApp As Object 
    Dim Documn As Object 
     
    Set DocApp = CreateObject("Word.Application") 
     
    DocApp.Visible = True 
    Set Documn = DocApp.Documents.Open("d:\Doc1.docx") 
     
    Documn.InlineShapes(1).OLEFormat.Object.Text = "大家好" 
    MsgBox "資料是：" & Documn.InlineShapes(1).OLEFormat.Object.Text 
    
'確認Shape名稱
'丟入即時運算視窗
? Selection.ShapeRange.Name

'改變Picture Content Control的Picture
With Wrddoc
Set oCC1 = .SelectContentControlsByTitle("TabPic").Item(1)
oCC1.Range.InlineShapes.AddPicture Filename:="X:\XFER\ANDREW-T\DCD " _
       & LblVL & "Tabs\" & TermPlt & ".jpg", LinkToFile:=False, _
        Range:=oCC1.Range, SaveWithDocument:=True
End With
'Format the shape
With Wrddoc.oCC1.Range.InlineShapes(1)
    .LockAspectRatio = msoTrue
    .ScaleHeight 0.3, True 'height scaled to 30% of original picture size
    .ScaleWidth 0.3, True 'width scaled to 30% of original picture size
    .WrapFormat.AllowOverlap = False
    .WrapFormat.Side = 1 'wdWrapLeft
    .WrapFormat.Type = 0 'wdWrapSquare
End With

'將圖片放在書籤設定的位置
On Error GoTo TabErrorHandler
Set oCC1 = WordApp.ActiveDocument.Bookmarks("TabPic")
    oCC1.Range.InlineShapes.AddPicture Filename:=ActiveWorkbook.Path & "\DCD " & LblVL & "Tabs\" & TermPlt & ".jpg", LinkToFile:=False, _
    Range:=oCC1.Range, SaveWithDocument:=True
    
    If ConvKit.Value = False Then
    On Error GoTo LabelErrorHandler
Set oCC2 = WordApp.ActiveDocument.Bookmarks("LabelPic")
    oCC2.Range.InlineShapes.AddPicture Filename:=ActiveWorkbook.Path & "\DCD " & LblVL & "Labels\E" & LblVE & LblSB & LblPole & ".jpg", LinkToFile:=False, _
    Range:=oCC2.Range, SaveWithDocument:=True
    End If
   
'convert a InlineShape to a Shape
' \\ This sub will convert a InlineShape to a Shape
Sub ConvertToShape() 
    With Selection 
         ' \\ If we selected a InlineShape then convert to Shape
        If .Type = wdSelectionInlineShape Then 
            .InlineShapes(1).ConvertToShape 
        End If 
    End With 
End Sub 
 
 ' \\ This sub will convert a Shape to a InlineShape
Sub ConvertToInlineShape() 
    With Selection 
         ' \\ If we selected a Shape then convert to InlineShape
        If .Type = wdSelectionShape Then 
            .ShapeRange(1).ConvertToInlineShape 
        End If 
    End With 
End Sub 
